# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name': '\u6295\u7968'},
        ),
        migrations.AlterModelTable(
            name='polls',
            table='polls',
        ),
    ]
